export const DEFAULT_LANGUAGE = 'en';
export const SUPPORTED_LANGUAGES = ['en', 'fr'] as const;
export type SupportedLanguage = typeof SUPPORTED_LANGUAGES[number];

// Professional roles for mentor application form
export const PROFESSIONAL_ROLES = [
  'Software Engineer',
  'Data Scientist',
  'Data Engineer',
  'Machine Learning Engineer',
  'AI Researcher',
  'Product Manager',
  'UX Designer',
  'UI Designer',
  'Full Stack Developer',
  'Frontend Developer',
  'Backend Developer',
  'Mobile Developer',
  'DevOps Engineer',
  'Cloud Engineer',
  'Solutions Architect',
  'Business Analyst',
  'Project Manager',
  'Scrum Master',
  'Technical Writer',
  'QA Engineer',
  'Security Engineer',
  'Blockchain Developer',
  'Game Developer',
  'AR/VR Developer',
  'IoT Engineer',
  'Robotics Engineer',
  'Embedded Systems Engineer',
  'Network Engineer',
  'Systems Administrator',
  'Database Administrator',
  'Marketing Specialist',
  'Digital Marketing Manager',
  'SEO Specialist',
  'Content Creator',
  'Business Development Manager',
  'Sales Manager',
  'Academic Researcher',
  'Professor/Instructor',
  'Education Consultant',
  'Financial Analyst',
  'Investment Banker',
  'Consultant',
  'Entrepreneur',
  'Startup Founder',
  'Executive (C-level)',
  'HR Specialist',
  'Recruitment Specialist',
  'Other'
].sort();

// Areas of interest for mentor application form
export const AREAS_OF_INTEREST = [
  'Artificial Intelligence',
  'Machine Learning',
  'Deep Learning',
  'Natural Language Processing',
  'Computer Vision',
  'Data Science',
  'Big Data',
  'Data Engineering',
  'Data Analytics',
  'Business Intelligence',
  'Web Development',
  'Mobile Development',
  'Full Stack Development',
  'Frontend Development',
  'Backend Development',
  'DevOps',
  'Cloud Computing',
  'Cybersecurity',
  'Blockchain',
  'Cryptocurrency',
  'Game Development',
  'Augmented Reality',
  'Virtual Reality',
  'Internet of Things',
  'Robotics',
  'Product Management',
  'Project Management',
  'UX/UI Design',
  'Digital Marketing',
  'Social Media Marketing',
  'Content Marketing',
  'SEO',
  'SEM',
  'E-commerce',
  'Business Development',
  'Sales',
  'Entrepreneurship',
  'Startup Building',
  'Finance',
  'Investment',
  'Accounting',
  'Human Resources',
  'Leadership',
  'Management',
  'Public Speaking',
  'Technical Writing',
  'Education Technology',
  'Healthcare Technology',
  'FinTech',
  'Renewable Energy',
  'Sustainability',
  'Social Impact',
  'Consulting',
  'Market Research',
  'International Business',
  'Supply Chain Management',
  'Operations Management',
  'Customer Experience',
  'Other'
].sort();