// Helper function to get country name from country code
export const getCountryName = (code: string): string => {
  const countryMap: Record<string, string> = {
    'us': 'United States',
    'uk': 'United Kingdom',
    'gb': 'United Kingdom',
    'ca': 'Canada',
    'au': 'Australia',
    'in': 'India',
    'fr': 'France',
    'de': 'Germany',
    'jp': 'Japan',
    'es': 'Spain',
    'sn': 'Senegal',
    'br': 'Brazil',
    'mx': 'Mexico',
    'it': 'Italy',
    'nl': 'Netherlands',
    'ch': 'Switzerland',
    'at': 'Austria',
    'be': 'Belgium',
    'se': 'Sweden',
    'no': 'Norway',
    'dk': 'Denmark',
    'fi': 'Finland',
    'pt': 'Portugal',
    'pl': 'Poland',
    'cz': 'Czech Republic',
    'hu': 'Hungary',
    'gr': 'Greece',
    'tr': 'Turkey',
    'ma': 'Morocco',
    'eg': 'Egypt',
    'za': 'South Africa',
    'ng': 'Nigeria',
    'ke': 'Kenya',
    'gh': 'Ghana',
    'cn': 'China',
    'kr': 'South Korea',
    'th': 'Thailand',
    'sg': 'Singapore',
    'my': 'Malaysia',
    'id': 'Indonesia',
    'ph': 'Philippines',
    'vn': 'Vietnam',
    'ar': 'Argentina',
    'cl': 'Chile',
    'co': 'Colombia',
    'pe': 'Peru',
    'uy': 'Uruguay',
    'ru': 'Russia',
    'ua': 'Ukraine',
    'il': 'Israel',
    'ae': 'United Arab Emirates',
    'sa': 'Saudi Arabia',
    'jo': 'Jordan',
    'lb': 'Lebanon',
    'ir': 'Iran',
    'pk': 'Pakistan',
    'bd': 'Bangladesh',
    'lk': 'Sri Lanka',
    'np': 'Nepal'
  };
  
  return countryMap[code] || code.toUpperCase();
};

// List of countries for dropdowns
export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'India',
  'France',
  'Germany',
  'Japan',
  'Spain',
  'Senegal',
  'Brazil',
  'Mexico',
  'Italy',
  'Netherlands',
  'Switzerland',
  'Austria',
  'Belgium',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Portugal',
  'Poland',
  'Czech Republic',
  'Hungary',
  'Greece',
  'Turkey',
  'Morocco',
  'Egypt',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Ghana',
  'China',
  'South Korea',
  'Thailand',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Philippines',
  'Vietnam',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'Uruguay',
  'Russia',
  'Ukraine',
  'Israel',
  'United Arab Emirates',
  'Saudi Arabia',
  'Jordan',
  'Lebanon',
  'Iran',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'Nepal'
].sort(); 