// Helper function to get country name from country code
export const getCountryName = (code: string): string => {
  const countryMap: Record<string, string> = {
    'us': 'United States',
    'uk': 'United Kingdom',
    'gb': 'United Kingdom',
    'ca': 'Canada',
    'au': 'Australia',
    'in': 'India',
    'fr': 'France',
    'de': 'Germany',
    'jp': 'Japan',
    'es': 'Spain',
    'sn': 'Senegal',
    'br': 'Brazil',
    'mx': 'Mexico',
    'it': 'Italy',
    'nl': 'Netherlands',
    'ch': 'Switzerland',
    'at': 'Austria',
    'be': 'Belgium',
    'se': 'Sweden',
    'no': 'Norway',
    'dk': 'Denmark',
    'fi': 'Finland',
    'pt': 'Portugal',
    'pl': 'Poland',
    'cz': 'Czech Republic',
    'hu': 'Hungary',
    'gr': 'Greece',
    'tr': 'Turkey',
    'ma': 'Morocco',
    'eg': 'Egypt',
    'za': 'South Africa',
    'ng': 'Nigeria',
    'ke': 'Kenya',
    'gh': 'Ghana',
    'cn': 'China',
    'kr': 'South Korea',
    'th': 'Thailand',
    'sg': 'Singapore',
    'my': 'Malaysia',
    'id': 'Indonesia',
    'ph': 'Philippines',
    'vn': 'Vietnam',
    'ar': 'Argentina',
    'cl': 'Chile',
    'co': 'Colombia',
    'pe': 'Peru',
    'uy': 'Uruguay',
    'ru': 'Russia',
    'ua': 'Ukraine',
    'il': 'Israel',
    'ae': 'United Arab Emirates',
    'sa': 'Saudi Arabia',
    'jo': 'Jordan',
    'lb': 'Lebanon',
    'ir': 'Iran',
    'pk': 'Pakistan',
    'bd': 'Bangladesh',
    'lk': 'Sri Lanka',
    'np': 'Nepal'
  };
  
  return countryMap[code.toLowerCase()] || code.toUpperCase();
};

// Helper function to get country code from country name for form submissions
export const getCountryCode = (countryName: string): string => {
  const reverseMap: Record<string, string> = {
    'United States': 'US',
    'United Kingdom': 'UK', 
    'Canada': 'CA',
    'Australia': 'AU',
    'India': 'IN',
    'France': 'FR',
    'Germany': 'DE',
    'Japan': 'JP',
    'Spain': 'ES',
    'Senegal': 'SN',
    'Brazil': 'BR',
    'Mexico': 'MX',
    'Italy': 'IT',
    'Netherlands': 'NL',
    'Switzerland': 'CH',
    'Austria': 'AT',
    'Belgium': 'BE',
    'Sweden': 'SE',
    'Norway': 'NO',
    'Denmark': 'DK',
    'Finland': 'FI',
    'Portugal': 'PT',
    'Poland': 'PL',
    'Czech Republic': 'CZ',
    'Hungary': 'HU',
    'Greece': 'GR',
    'Turkey': 'TR',
    'Morocco': 'MA',
    'Egypt': 'EG',
    'South Africa': 'ZA',
    'Nigeria': 'NG',
    'Kenya': 'KE',
    'Ghana': 'GH',
    'China': 'CN',
    'South Korea': 'KR',
    'Thailand': 'TH',
    'Singapore': 'SG',
    'Malaysia': 'MY',
    'Indonesia': 'ID',
    'Philippines': 'PH',
    'Vietnam': 'VN',
    'Argentina': 'AR',
    'Chile': 'CL',
    'Colombia': 'CO',
    'Peru': 'PE',
    'Uruguay': 'UY',
    'Russia': 'RU',
    'Ukraine': 'UA',
    'Israel': 'IL',
    'United Arab Emirates': 'AE',
    'Saudi Arabia': 'SA',
    'Jordan': 'JO',
    'Lebanon': 'LB',
    'Iran': 'IR',
    'Pakistan': 'PK',
    'Bangladesh': 'BD',
    'Sri Lanka': 'LK',
    'Nepal': 'NP'
  };
  
  return reverseMap[countryName] || countryName;
};

// List of countries for dropdowns
export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'India',
  'France',
  'Germany',
  'Japan',
  'Spain',
  'Senegal',
  'Brazil',
  'Mexico',
  'Italy',
  'Netherlands',
  'Switzerland',
  'Austria',
  'Belgium',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Portugal',
  'Poland',
  'Czech Republic',
  'Hungary',
  'Greece',
  'Turkey',
  'Morocco',
  'Egypt',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Ghana',
  'China',
  'South Korea',
  'Thailand',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Philippines',
  'Vietnam',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'Uruguay',
  'Russia',
  'Ukraine',
  'Israel',
  'United Arab Emirates',
  'Saudi Arabia',
  'Jordan',
  'Lebanon',
  'Iran',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'Nepal'
].sort(); 